---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 443, host: 4443}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2012R2
    transport:
      name: winrm
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[rdp_443::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
